### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by balloob** [runem/lit-analyzer#55] opened 2019-09-21 06:31 UTC
TypeScript version: 3.5.1 & 3.6.3
(lit-analyzer has no `--version` btw)
lit-analyzer version: 1.1.8

When I run it against any file in the [Home Assistant Polymer repo](https://github.com/home-assistant/home-assistant-polymer/), I get this error:

```
TypeError: Cannot read property 'kind' of undefined
    at isDeclarationNameOrImportPropertyName (/Users/paulus/dev/hass/home-assistant-polymer/node_modules/typescript/lib/typescript.js:61175:29)
    at getTypeOfNode (/Users/paulus/dev/hass/home-assistant-polymer/node_modules/typescript/lib/typescript.js:58919:17)
    at Object.getTypeAtLocation (/Users/paulus/dev/hass/home-assistant-polymer/node_modules/typescript/lib/typescript.js:31456:31)
    at /Users/paulus/dev/hass/home-assistant-polymer/node_modules/ts-simple-type/lib/index.cjs.js:593:55
    at Array.map (<anonymous>)
    at toSimpleTypeInternal (/Users/paulus/dev/hass/home-assistant-polymer/node_modules/ts-simple-type/lib/index.cjs.js:590:59)
    at toSimpleTypeInternalCaching (/Users/paulus/dev/hass/home-assistant-polymer/node_modules/ts-simple-type/lib/index.cjs.js:351:33)
    at /Users/paulus/dev/hass/home-assistant-polymer/node_modules/ts-simple-type/lib/index.cjs.js:593:19
    at Array.map (<anonymous>)
    at toSimpleTypeInternal (/Users/paulus/dev/hass/home-assistant-polymer/node_modules/ts-simple-type/lib/index.cjs.js:590:59)
```

I went ahead and put a `console.log(name)` there to see which `name` has a `parent` which is `undefined` and traced it back to this file:

https://www.unpkg.com/@types/chromecast-caf-receiver@3.0.12/cast.framework.d.ts

That file is imported [here](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/cast/cast_manager.ts#L8-L12) (although I don't think that matters)

I tried creating a repro by just `npm install typescript lit-analyzer @types/chromecast-caf-receiver` but was unable to reproduce it. I might give creating repro another stab when I have time.

**Comment by runem** [comment] 2019-09-21 20:47
Hi, thanks for your issue! 

The error `TypeError: Cannot read property 'kind' of undefined` typically comes because of a mismatch between the TS version being used for parsing and the TS version being used when visiting the AST. However, I make sure to use the same TS module everywhere in the code. I'll make sure to double check that this is actually the case everywhere.

I tried to clone the repo and install `lit-analyzer`, but everything worked fine. What does `npm ls typescript` outputs for you? Mine outputs:

```
home-assistant-frontend@1.0.0
├─┬ lit-analyzer@1.1.8
│ └─┬ web-component-analyzer@0.1.16
│   └── typescript@3.6.3  deduped
└── typescript@3.6.3
```

I'll also take a look at `cast.framework.d.ts` to test if all types can be analyzed without crashing. 

Be aware that right now `lit-analyzer` outputs some lit-element specific warnings related to property-metadata that cannot be turned off using rules. I'll make sure to include these as rules asap. Also note that CSS validation cannot be fined controlled right now. `--rules.no-invalid-css off` will turn all CSS validation off. In addition there is also a property "route" on "partial-panel-resolve" that seems to be analyzed as being a `string` and not a `Route` - I'll look into that :-)

I'll remember to add a `--version` flag to the CLI :+1:

**Comment by balloob** [comment] 2019-09-22 05:27
Thanks for the help! Frustrating it works for you and not for me. But that is at least a good start, it means it's local. Normally use `yarn`, but also tried doing `npm install` with no lock file, same issue. I'll continue to play with it.

I get the same output for `npm ls typescript`. I'm on node 12.1.0.

**Comment by runem** [comment] 2019-10-17 20:38
https://github.com/runem/lit-analyzer/issues/58 might be related

**Comment by bramkragten** [comment] 2020-04-14 14:57
Hi!

Following up on this, I just tried it again but I also get that error with version `1.1.10`. 
If I remove `@types/chromecast-caf-receiver@3.0.12` it does work, so it seems to be a compatibility issue with those types, not sure if that is something you can fix or should be fixed in the types?

Thanks for your help!

**Comment by balloob** [comment] 2020-04-14 17:27
I was able to repro it. It is caused because we have 2 Chromecast related types: 
`@types/chromecast-caf-receiver@5.0.4` and `@types/chromecast-caf-sender@1.0.3`.

I have put up a repro here https://github.com/balloob/lit-analyzer-bug-55

**Comment by runem** [comment] 2020-07-08 11:17
First of all, I'm sorry this issue has been stale for so long. I can't reproduce the issue it on your repro using the beta version `lit-analyzer@1.2.0-next.1` so it seems to be fixed in this PR: https://github.com/runem/lit-analyzer/pull/112.

I'll close this issue when the PR has been merged into master and published.

**Closed** 2020-07-15 18:54 UTC
Labels: bug
