### ISSUE TITLE
When input type is date, min and max should accept date string

### ISSUE THREAD

**Issue by alexjamesmalcolm** [runem/lit-analyzer#77] opened 2019-12-25 19:24 UTC
From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)'s documentation
> You can use the min and max attributes to restrict the dates that can be chosen by the user. In the following example, we sett a minimum date of 2017-04-01 and a maximum date of 2017-04-30

When I was attempting to programmatically set min to the current date
```javascript
html`<input type="date" min=${new Date().toISOString().split("T")[0]} />`
```
I received an error stating:
> Type 'string' is not assignable to 'number' no-incompatible-type-binding(2322)

This may be a duplicate of #43

**Comment by runem** [comment] 2019-12-27 11:46
Thanks for reporting this issue! Yes, this seems like a duplicate of #43, but I'm fine hotfixing specific attributes until #43 has been resolved :+1: 

[This file](https://github.com/runem/lit-analyzer/blob/master/packages/lit-analyzer/src/analyze/data/extra-html-data.ts) is a way to overwrite specific attributes, so if you find other invalid attribute types, feel free to fix it there :blush: 

I now added `string` to the type set of `min` and `max`. Until this fix has been published I suggest you to set the corresponding properties `.min` and `.max` instead which I see are already of `string` type.

**Closed** 2019-12-27 11:47 UTC
