### ISSUE TITLE
The status and future of the project is unclear

### ISSUE THREAD

**Issue by DemiusAcademius** [runem/lit-analyzer#219] opened 2021-12-22 06:29 UTC
Hello!
Thanks for great work!
The status and future of the project is unclear.
Will there be any further development?
Will there be new versions coming out?

Unfortunately, the excellent LIT library is useless without a good ecosystem.

And for serious projects you will have to choose other libraries.

**Comment by mgenware** [comment] 2022-01-10 17:10
Same question here. I've convinced my team to migrate to lit and this plugin and #200 has been blocking us from using vscode typescript auto-import for almost 5 months.

**Comment by dethell-banno** [comment] 2022-01-15 11:21
Same here. Our team is all-in with Lit and this plugin is/was pretty instrumental to our VS Code setup. Need the auto-imports to work again so for now we just all disabled this plugin, but that has hurt our Lit development in many ways.

**Comment by jjspace** [comment] 2022-01-21 17:00
As an imperfect solution I've anchored my VSCode version to 1.59 so this plugin still works with auto-import but I'm getting more and more annoyed I can't use the newer VSCode features. However as everyone else here stated, this plugin is essential to working in our entirely Lit based application...

**Comment by justinfagnani** [comment] 2022-01-21 17:26
Hello all 👋 

The Lit team is ramping up contribution and maintenance of the projects here. We realize they're critical to the Lit developer experience and are going to invest a lot more time in continuing @runem's excellent work here.

For some idea of the work happening: I made some changes last year to support Lit 2 features and untangle some TypeScript compiler dependency issues, but wasn't able to get a working updated VS Code extension published. @43081j has been investigating why the extension breaks and has a lead on that due to an extension API change. @rictic is now taking lead on this from the Lit team and is starting with getting an extension test harness up (https://github.com/runem/lit-analyzer/pull/224) so that we can make sure we have a working extension from CI.

The goal is to publish a new VS code extension as soon as possible.

In addition to that we're working on a new focused analysis library in the Lit monorepo. We need this in Lit for SSR and other tools, and it'l be good to have a core-team maintained and tested analysis library that linters, etc can build off of.

I hope that helps with the questions!

**Comment by DemiusAcademius** [comment] 2022-01-22 07:43
thanks for the encouraging news and great work

пт, 21 янв. 2022 г., 19:27 Justin Fagnani ***@***.***>:

**Comment by jjspace** [comment] 2023-06-06 19:57
We have [once again](https://github.com/runem/lit-analyzer/issues/200#issuecomment-1063201529) gone almost 3 months with a "broken" plugin due to VSCode update [v1.77 switching to TS 5.0](https://code.visualstudio.com/updates/v1_77#_typescript-50). `lit-analyzer`, and by extension `lit-plugin`, does not work on TS 5.0 as outlined in multiple issues that have been opened since:

- https://github.com/runem/lit-analyzer/issues/302
- https://github.com/runem/lit-analyzer/issues/299
- https://github.com/runem/lit-analyzer/issues/301

I noticed that there is now an [`analyzer`](https://www.npmjs.com/package/@lit-labs/analyzer) package being worked on in the [Lit labs](https://lit.dev/docs/libraries/labs/). I assume that's the "focused analysis library" mentioned above. It looks like it's still "not ready for use" so what is the progress of that over the past year+? Is the intention to replace this package with that one? Is there any timeline on when that might be ready? Will this package/plugin still receive any updates/support until that analyzer is ready?

CC @justinfagnani @43081j @bicknellr @rictic

**Comment by 43081j** [comment] 2023-06-06 22:33
this is really caused by the fact that we're in limbo right now - the lit team took over responsibilities of this repo, with difficulty, and later started work on their own analyzer to ultimately replace this one.

however, it means they have no time to work on this "legacy" analyzer (afaict) and the replacement isn't yet ready (nowhere close i think).

i think we need to admit that this is very much still alive and needs maintaining until the replacement by the lit team actually exists and is useable enough that this package is no longer needed.

im away this week for a few days but, when im back, i will try fix up the current issues on a branch and get help from the lit team to publish it as a new version. 

@rictic @justinfagnani if you can help code review and publish once i manage to do the fixes, that'd be much appreciated

**Comment by 43081j** [comment] 2023-06-13 18:30
update for anyone following, fixes will be in this pr: #305

**Comment by rictic** [comment] 2023-06-20 18:33
PRs merged and released, huge thanks to @43081j for his work on this!

**Closed by rictic** 2023-06-20 18:33 UTC
