### ISSUE TITLE
TypeScript import from suggestions no longer works after enabling lit-plugin

### ISSUE THREAD

**Issue by Artur-** [runem/lit-analyzer#200] opened 2021-09-16 08:34 UTC
https://user-images.githubusercontent.com/260340/133578989-1d30d980-3e4d-4b11-943d-d2aac37c6e1a.mov

https://user-images.githubusercontent.com/260340/133578779-1a73a8dd-fa18-4aed-8065-1715c85a403f.mov

**Comment by jjspace** [comment] 2021-09-16 14:54
Just commenting to make sure this is linked back to the original issue opened in the VSCode repo which may have more information. https://github.com/microsoft/vscode/issues/132299

Also this is specifically only happening on version 1.60+ of VSCode, everything was working fine in version 1.59 so something changed with that release.

I can also confirm that this happens for normal `.js` files as well, it's not limited to typescript

**Comment by luvsic3** [comment] 2021-09-18 09:58
Same problem happens on my vscode

**Comment by Kokujou** [comment] 2021-09-21 07:50
same problem for me. just wanted to add: there is no specific extension configuration, all other extensions have been uninstalled to verify that it is really this extensions. further it is not about typescript alone.
the project i'm working with is javascript based and is only using relative imports (no node_modules or NPM imports)

**Comment by Artur-** [comment] 2021-09-21 08:02
This is from the (closed) VS Code issue about how it can be reproduced: https://github.com/microsoft/vscode/issues/132299#issuecomment-921077717

**Comment by Artur-** [comment] 2021-09-21 08:03
The only thing I found while digging around is that this could possibly related to `getCompletionEntryDetails` having an additional parameter in TS 4.4 that is not present at least in 4.2

https://github.com/runem/lit-analyzer/blob/56489d04242b35d692b1db4d0f776f9ca0da19b9/packages/ts-lit-plugin/src/ts-lit-plugin/ts-lit-plugin.ts#L45-L59 is what is causing the problem

**Comment by 43081j** [comment] 2021-09-28 18:34
@justinfagnani i think artur may be right. 4.x of typescript brought in an extra parameter, `data`, to the `getCompletionEntryDetails`.

i suppose if we're using the user's local typescript, they could be on 4.x which would lead to the `data` parameter being lost when it goes through the code here? as we'd pass through to `prevLangService` without that parameter.

in order to update lit-analyzer to ts 4.x, though, i think we need to update web-component-analyzer first.

**Comment by Kokujou** [comment] 2021-10-13 07:39
so what do you think, will there be a fix soon? do you need to assign some responsible person for this bug? 
i would think the priority is kinda high because it breaks an important functionality. 
for me and my team it would gain more and more importance.

**Comment by vdegenne** [comment] 2021-12-04 10:47
Any updates? There is a pending pull request.
This issue is driving me nut, I have to import all symbols manually.

**Comment by Kokujou** [comment] 2021-12-04 17:11
well you could also disable this extension instead... 
or, if you want to be very clever, you can install the extension manually from the branch the PR is on^^

**Comment by 43081j** [comment] 2021-12-06 08:44
We're waiting on runem/web-component-analyzer#236, justin and peter are pretty busy with lit and i don't have access to merge/publish, so unfortunately i can't do much yet.

if the new WCA version gets published, we can then merge #206 i think

**Comment by jjspace** [comment] 2021-12-24 16:38
@43081j any way we can move this along? We're now 3 versions behind VSCode (being locked to v1.59) and I'd really like to update but I use `lit-plugin` all day every day so I don't feel comfortable going to 1.60+ until this is fixed...

**Comment by 43081j** [comment] 2021-12-24 22:31
Unfortunately we're still blocked until @justinfagnani can find some time to merge the related PRs and publish a new version. 

I'll see if I can catch up with him and Peter again after Christmas and get this sorted

**Comment by jjspace** [comment] 2022-03-09 17:56
Bump, another 2 months with little movement... Am I correct that this is just waiting on #206 which is in turn waiting on a deploy of web-components-analyzer? Is that where we're at? everything is in place it just needs to get released/merged?

I'm genuinely confused/interested how other people work with Lit without a tool like this to help them see syntax and have completions. How do the developers of Lit itself even work with it? Or are we all just putting up with the out of date plugin on an old version of VSCode like I am...? Or maybe just putting up with manually importing?

CC @43081j @rictic @justinfagnani

**Comment by Kokujou** [comment] 2022-03-09 18:24
honestly if it' sjust waiting for a simple PR to be merged and the code is already there, i wish someone would just clone this repo and make a temporary release until this stuff is properly integrated into the release. but maybe i'm not understanding what exactly is missing.

**Comment by blikblum** [comment] 2022-03-09 23:35
> I'm genuinely confused/interested how other people work with Lit

I removed this plugin. Really miss it. Even with this plugin working, the IDE support to Lit ecosystem is subpar compared to e.g. React or Angular. Its one of the drawbacks of using Lit

**Comment by 43081j** [comment] 2022-03-10 19:21
im really sorry for the slowness here. 

what we are waiting on:

* web-component-analyzer needs publishing (new version)
* lit-analyzer needs to then depend on the new version
* #206 needs merging

there's nothing difficult left to do as far as im aware. i don't have permissions to merge and publish these things myself, so im waiting on @rictic or @justinfagnani to do it. both are pretty busy people though so progress hasn't been great.

i will try catch up with them again soon if i can get hold of them, and maybe we can get this stuff finally merged and sorted

**Closed** 2022-04-04 17:23 UTC

**Comment by jjspace** [comment] 2022-04-04 18:42
Thanks so much for your work on this @rictic and @43081j! :pray: Looking forward to a release of the plugin to roll out so I can finally upgrade my vscode :tada:

**Comment by rictic** [comment] 2022-04-26 18:32
Forgot to update here last week but the updated version is now released!

**Comment by vdegenne** [comment] 2022-05-04 17:41
Are **auto-closing** features not working or are they just not implemented?
I was wishing this update would fix that but it doesn't (even though auto-import works now) or am I just missing something?

By **auto-closing** Here's an instance of what I mean :  
In a string literal if I start to type `dis` the auto-completion box opens and offer me to select `display` to go faster.
If I select it, it auto-completes the term but not the punctuations as it does in a dedicated file : 

What I get in an element context : 
```javascript
static styles = css`
#header {
  display<cursor>
}
`
```

What I get in an html file : 
```html
<style>
#header {
  display:<cursor>;
}
</style>
```

Wouldn't that be easy to implement? If it's just a matter of forwarding an attribute to the IDE options.

**Comment by 43081j** [comment] 2022-05-05 08:21
interesting, we don't interfere with that stuff as far as i know so it could be some state we're losing.

ill see if i can reproduce it in a test this weekend

**Comment by towry** [comment] 2023-03-07 07:09
Mine was caused by the volar extension.
