### ISSUE TITLE
Allow to disable rules in strict mode

### ISSUE THREAD

**Issue by hanc2006** [runem/lit-analyzer#81] opened 2020-01-29 21:00 UTC
Hi,
currently if I use the "strict" mode and I want to disable a specific rule, this automatically disables the "strict" mode.

**Example:**
` "lit-plugin.strict": true,`
` "lit-plugin.rules.no-complex-attribute-binding": "off",`

**Expected result:**
All "strict" rules active, without the disabled rule above.

**Current result:**
Strict mode is disabled.

This behavior does not happen if instead I put the rule notification in "warning"

**Comment by runem** [comment] 2020-07-08 21:18
Thanks for reporting this issue, I'm sorry for the late answer!

I've been making a lot of changes on this PR: https://github.com/runem/lit-analyzer/pull/112 and I can't reproduce your problem in that PR. Therefore I expect this issue to be fixed and I will close it when the PR has been released and merged into master.

Feel free to test out the beta version of the plugin by downloading and installing this `.vsix` file: https://github.com/runem/lit-analyzer/suites/892943037/artifacts/10623637 in order to test if you can reproduce the issue :-)

**Closed** 2020-07-15 18:54 UTC
